language: python
python:
  - 3.5
install:
  - sudo apt-get install graphviz
  - pip install sphinx sphinx_rtd_theme sphinxcontrib-plantuml sphinx-jsonschema sphinxcontrib-contentui
script: make html
after_success:
  - ./push.sh
